
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygenerator-generic
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - Generic
  controls: 
    - Generic
  namespace: policies
  # Use an existing placement rule 
  placement:
    placementPath: ../placement-example.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - Generic
policies:
- name: kyverno-generate
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/generate
- name: kyverno-mutate
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/mutate
- name: kyverno-validate
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno/validate    
