apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generic
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  # Use an existing placement rule 
  placement:
    placementPath: ../placement-example.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - generic
policies:
- name: policy-multiclusterhub
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/mulitclusterhub/MultiClusterHub.yaml
  complianceType: "mustonlyhave"
- name: policy-configure-backup-restore-restore
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/hub_backup_restore/dataprotectionresource.yaml  
 - name: policy-configure-backup-restore-passive
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/hub_backup_restore/dataprotectionresource.yaml
 - name: policy-configure-backup-restore-active
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/hub_backup_restore/dataprotectionresource.yaml    
    
