apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policies-appset-placement
  namespace: policies-appset
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: cluster-name, operator: In, values: ["local"]}
