apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-namespace-nist
placementBindingDefaults:
  name: binding-example
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  # Use an existing placement rule 
  placement:
    placementPath: ../placement-example.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - BsiGrundschutz
policies:
- name: policy-example-bsi-grundschutzii
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/input_policy1/
