apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: quota-limit-cluster-role
rules:
- apiGroups: [""] #specifies core api groups
  resources: ["resourcequotas", "limitranges"]
  verbs: ["create"]
Copy snippet
Enter the following command to create the ClusterRole on the cluster:

$ oc create -f <cluster-role-file-name>.yaml
Copy snippet
The configuration for a cluster role binding looks like this:

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows Service Account to create resource quotas and limit ranges in any namespace.
kind: ClusterRoleBinding
metadata:
  name: create-quota-limit-global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quota-limit-cluster-role # Name of cluster role to be referenced
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
