apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygenerator-generic
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - Generic
  controls: 
    - Generic
  namespace: policies
  # Use an existing placement rule 
  placement:
    placementPath: ../placement-example.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - Generic
  
policies:
- name: kyverno-all
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/kyverno
- name: policy-submariner
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/configurations/submariner/submariner-templatized-aws.yaml
- name: policy-gitops
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/operators/gitopsoperator.yaml
- name: policy-argoapp
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/gitops
- name: policy-certmanagerfull
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/certmanager
