apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygenerator-generic
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - Generic
  controls: 
    - Generic
  namespace: policies
  # Use an existing placement rule 
  placement:
    placementPath: ../placement-example.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - Generic
policies:
- name: policy-aap
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests: ../input/ansible/aap-operator.yaml
- name: policy-automationhub
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/ansible/automation-hub.yaml
- name: policy-multiclusterhub
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/mulitclusterhub/ 
- name: policy-gitopsoperator
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/operators/gitopsoperator.yaml
- name: policy-argoapp
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../input/gitops

