apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygenerator-generic
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - Generic
  controls: 
    - Generic
  namespace: policies
  # Use an existing placement rule 
  placement:
    placementPath: ../placement-example.yaml
  remediationAction: enforce
  severity: medium
  standards:
    - Generic
policies:
- name: policy-aap
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests: ../input/ansible/aap-operator.yaml
