apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-appset
  namespace: kyverno
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: red-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: kyverno-{{name}}
    spec:
      source:
        repoURL: https://kyverno.github.io/kyverno
        chart: kyverno
        targetRevision: '*
      destination:
        namespace: kyverno
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true

