apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: kyverno
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: red-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: kyverno-policies-{{name}}
    spec:
      project: kyverno-policies
      source:
        repoURL: https://github.com/rokej/BlueApplications.git
        targetRevision: main
        path: mobileApplication
      destination:
        namespace: kyverno
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true


