apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-policies
  namespace: kyverno-policies
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: NotIn
              value: true
        requeueAfterSeconds: 180
  template:
    metadata:
      name: kyverno-policies-{{name}}
    spec:
      project: kyverno-policies
      source:
        path: config/input/gitopsdemo/all/kyverno
        repoURL: https://github.com/ch-stark/maptoseveralstandards.git
        targetRevision: HEAD
      destination:
        namespace: kyverno
        server: "{{server}}"
    ignoreDifferences:
      - group: kyverno.io
        kind: ClusterPolicy
        jqPathExpressions:
          - .spec.rules[] | select(.name|test("autogen-."))         
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        selfHeal: true
