apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-policies
  namespace: kyverno-policies
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            useKyverno: yes
        requeueAfterSeconds: 180
  template:
    metadata:
      name: mobileapp-{{name}}
	spec:
	  project: default
	  source:
	    repoURL: https://kyverno.github.io/kyverno
	    chart: kyverno-policies
	    targetRevision: '*'
	  destination:
	    server: https://kubernetes.default.svc
	    namespace: kyverno
	      syncPolicy:
		syncOptions:
		  - CreateNamespace=true
		automated:
		  selfHeal: true

