apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policies-application-set
  namespace: policies-appset
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: policies-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: mobileapp-{{name}}
    spec:
      project: policies-project
      source:
        repoURL: https://github.com/rokej/BlueApplications.git
        targetRevision: main
        path: mobileApplication
      destination:
        namespace: bluemobileapp
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
