kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test
  name: permissions
rules:
- apiGroups: ["apps.open-cluster-management.io", "cluster.open-cluster-management.io"] # "" indicates the core API group
  resources: ["placementrules", "placementdecisions"]
  verbs: ["list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: permission-rolebinding
  namespace: test
subjects:
- kind: ServiceAccount
  name: test-applicationset-controller
  namespace: test
roleRef:
  kind: Role
  name: permissions
  apiGroup: rbac.authorization.k8s.io

---



kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: redteam
  name: permissions
rules:
- apiGroups: ["apps.open-cluster-management.io", "cluster.open-cluster-management.io"] # "" indicates the core API group
  resources: ["placementrules", "placementdecisions"]
  verbs: ["list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: permission-rolebinding
  namespace: redteam
subjects:
- kind: ServiceAccount
  name: redteam-applicationset-controller
  namespace: redteam
roleRef:
  kind: Role
  name: permissions
  apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: blueteam
  name: permissions
rules:
- apiGroups: ["apps.open-cluster-management.io", "cluster.open-cluster-management.io"] # "" indicates the core API group
  resources: ["placementrules", "placementdecisions"]
  verbs: ["list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: permission-rolebinding
  namespace: blueteam
subjects:
- kind: ServiceAccount
  name: blueteam-applicationset-controller
  namespace: blueteam
roleRef:
  kind: Role
  name: permissions
  apiGroup: rbac.authorization.k8s.io
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redteam-p55gd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managedclusterset:admin:redteam
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: red-sre-group

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blueteam-p55gd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managedclusterset:admin:blueteam
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: blue-sre-group


